[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/buger/goterm"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.1.2"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.21.0"
